application: astrozac42
version: 1
runtime: python
api_version: 1

builtins:
- deferred: on

handlers:
- url: /javascript
  static_dir: javascript

- url: /css
  static_dir: css

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /admin
  login: admin
  script: admin.py

- url: /splash
  script: splash.py

- url: /api/.*
  login: required
  script: api.py

- url: /file
  login: required
  script: main.py

- url: /.*
  script: main.py
